### PR TITLE
Update the sample project

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
@svor do you think you could enable GitHub Actions for this repository? :pray:

**Review by svor — APPROVED** [review]

**Comment by svor** [comment]
> @svor do you think you could enable GitHub Actions for this repository? pray

Let's try it. In case I'll miss some PR's on this sample, please ping me

**Comment by svor** [comment]
@sideeffffect I see 4 more PRs in the repos, should we merge them as well?

**Comment by sideeffffect** [comment]
Yes. Or even better, enable Mergify for this repository
https://dashboard.mergify.com/github

**Pull request merged**
